export { default as ForgotPasswordScreen } from "./ForgetPasswordScreen";
export { default as GameOverScreen } from "./GameOverScreen";
export { default as GameScreen } from "./GameScreen";
export { default as LoginScreen } from "./LoginScreen";
export { default as RegisterScreen } from "./RegisterScreen";
export { default as ScoresScreen } from "./ScoresScreen";
export { default as StartScreen } from "./StartScreen";
export { default as SuccessScreen } from "./SuccessScreen";
export { default as WelcomePage } from "./WelcomePage";
